name: expenseTracker
services:
  db:
    image: postgres:15
    container_name: expenses-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: expenses
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  apollo-server:
    container_name: expenses-app
    build: server
    restart: unless-stopped
    environment:
      WAIT_HOSTS: db:5432
      WAIT_TIMEOUT: 60
      DATABASE_URL: postgresql://postgres:postgres@db:5432/expenses
      QUEUE_NAME: expenses_app_messages
      RABBITMQ_URL: amqp://localhost
      JWT_SECRET: myJWTSecret
    ports:
      - "127.0.0.1:4000:4000"
    depends_on:
      - db

  worker:
    container_name: expenses-worker
    build: ./worker
    restart: unless-stopped
    environment:
      RABBITMQ_URL: amqp://localhost
      QUEUE_NAME: expenses_app_messages
      AI_BASE_URL: http://expenses-ai:8000
      SERVER_BASE_URL: http://expenses-app:4000
      LLM_BASE_URL: ""
      JWT_SECRET: myJWTSecret

  sms-ai:
    build: sms_classifier
    container_name: expenses-ai
    restart: unless-stopped

volumes:
  pgdata:
