services:
  db:
    image: postgres:15
    container_name: expenses-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: expenses
    volumes:
      - pgdata:/var/lib/postgresql/data

  apollo-server:
    container_name: expenses-app
    build: .
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/expenses
      WAIT_HOSTS: db:5432
      WAIT_TIMEOUT: 60
    ports:
      - "4000:4000"
    depends_on:
      - db

volumes:
  pgdata:

